---
cops_deploy_ssh_key_paths:
  staging:
    path: "{{'local/.ssh/deploy_staging'|copsf_abspath}}"
    pub: |-
      ssh-rsa xxx aaa
    private: |-
      -----BEGIN RSA PRIVATE KEY-----
      xxx
      -----END RSA PRIVATE KEY-----
cops_pureftpd_ftp_admin_password: secret6c5f8P293Ma47Rn
