---
- when: ["cops_pureftpd_s_workers_service"]
  tags: ["cops_pureftpd_s_workers_service"]
  block:
  # activate the main app service
  - include_role: {name: corpusops.roles/services_ftp_pureftpd}
    vars:
      corpusops_services_ftp_pureftpd_prequisites: false
      corpusops_services_ftp_pureftpd_configuration: false
      corpusops_services_ftp_pureftpd_services: true
  # force a reload/restart here
  - shell: echo "force service reload/restart"
    notify: "{{cops_pureftpd_vars.rhandlers}}"
  - meta: flush_handlers
