---
- set_fact:
    cacheable: false
    cops_pureftpd_lifecycle_app: |-
     ((not vars.get('SKIP_INSTALL_PUREFTPD', False) and
       (cops_pureftpd_lifecycle_app|default(false))) or
      vars.get('FORCE_INSTALL_PUREFTPD', False))
