---
- set_fact:
    cacheable: false
    secretvariablel: "{{secretvariable}}"
- include_role: {name: corpusops.roles/utils/set_secret_variable}
  vars:
    secretvariable: "{{secretvariablel}}"
    cops_get_secret_variable_name: "cops_pureftpd_{{secretvariablel}}"
    cops_get_secret_variable_path: "/etc/{{cops_pureftpd_name}}-secrets"
    cops_secret_variable_registry_prefix: cops_pureftpd_
