---
- listen: restart_cops_pureftpd_systemd
  become: true
  shell: systemctl daemon-reload
  when: "(cops_pureftpd_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr == 'systemd'))"

- listen: restart_cops_pureftpd
  become: true
  systemd:
    daemon_reload: yes
    state: restarted
    name: "{{item}}"
  loop: "{{cops_pureftpd_vars.services}}"
  when: "(cops_pureftpd_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr == 'systemd'))"
- listen: restart_cops_pureftpd
  become: true
  service:
    state: restarted
    name: "{{item}}"
  loop: "{{cops_pureftpd_vars.services}}"
  when: "(cops_pureftpd_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr != 'systemd'))"

- listen: reload_cops_pureftpd
  become: true
  systemd:
    daemon_reload: yes
    state: reloaded
    name: "{{item}}"
  loop: "{{cops_pureftpd_vars.services}}"
  when: "(cops_pureftpd_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr == 'systemd'))"
- listen: reload_cops_pureftpd
  become: true
  service:
    state: reloaded
    name: "{{item}}"
  loop: "{{cops_pureftpd_vars.services}}"
  when: "(cops_pureftpd_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr != 'systemd'))"
