---
- when: [cops_pureftpd_s_prerequisites_pkgs]
  tags: [cops_pureftpd_s_prerequisites_pkgs]
  block:
  - name: update & install prerequisites
    package:
      cache_valid_time: '{{60*60}}'
      update_cache: yes
      name: '{{item}}'
      state: present
    when: "(ansible_os_family.lower() in ['debian'] and
            cops_pureftpd_vars.deb_packages is not none and
            cops_pureftpd_vars.deb_packages|length > 0)"
    loop: "{{cops_pureftpd_vars.deb_packages}}"
  - name: update & install prerequisites
    package:
      update_cache: yes
      enablerepo: epel,epel-testing
      name: '{{item}}'
      state: present
    when: "(ansible_os_family.lower() in ['redhat'] and
            cops_pureftpd_vars.rh_packages is not none and
            cops_pureftpd_vars.rh_packages|length > 0)"
    loop: "{{cops_pureftpd_vars.rh_packages}}"
- when: [cops_pureftpd_s_prerequisites_build_pkgs]
  tags: [cops_pureftpd_s_prerequisites_build_pkgs]
  block:
  - name: update & install build prerequisites
    package:
      cache_valid_time: '{{60*60}}'
      update_cache: yes
      name: '{{item}}'
      state: present
    when: "(ansible_os_family.lower() in ['debian'] and
            cops_pureftpd_vars.deb_build_packages is not none and
            cops_pureftpd_vars.deb_build_packages|length > 0)"
    loop: "{{cops_pureftpd_vars.deb_build_packages}}"
  - name: update & install build prerequisites
    package:
      update_cache: yes
      enablerepo: epel,epel-testing
      name: '{{item}}'
      state: present
    when: "(ansible_os_family.lower() in ['redhat'] and
            cops_pureftpd_vars.rh_build_packages is not none and
            cops_pureftpd_vars.rh_build_packages|length > 0)"
    loop: "{{cops_pureftpd_vars.rh_build_packages}}"

- include_role: {name: corpusops.roles/services_ftp_pureftpd}
  tags: [cops_pureftpd_s_prerequisites_pureftpd]
  when: [cops_pureftpd_s_prerequisites_pureftpd]
  vars:
    corpusops_services_ftp_pureftpd_do_prerequisites: true
    corpusops_services_ftp_pureftpd_do_configuration: false
    corpusops_services_ftp_pureftpd_do_services: false
